# Generated by Django 5.1 on 2024-08-31 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de933b04-454d-45b2-a75d-0152f97cf6dd'), primary_key=True, serialize=False),
        ),
    ]
